<Workspace Version="1.2.1.3083" X="-371.76245928122" Y="73.317962275682" zoom="0.754436314720004" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="de398f19-9dda-4448-b260-d97475bc1588" type="PythonNodeModels.PythonNode" nickname="DynamicSectionView:Python Script" x="1350.51715855688" y="54.146525929775" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import FilteredElementCollector as _FilteredElementCollector
from Autodesk.Revit.DB import ViewFamilyType as _ViewFamilyType

import System
from System import Array
from System.Collections.Generic import *

import sys


def get_ViewFamilyTypeId(viewFamilyTypeName):	
	names = []
	ids = []
	viewFamilyTypeId = -1
	collector = _FilteredElementCollector(doc).OfClass(_ViewFamilyType) #collecting all elements of type ViewFamilyType
	for t in collector:
		names.append(t.FamilyName)
		ids.append(t.Id)
		if t.FamilyName == viewFamilyTypeName:
			viewFamilyTypeId = t.Id
			break # get the first
	return viewFamilyTypeId
			
			
def create_view(doc, viewFamilyTypeId, boundingBox):			
	if viewFamilyTypeId != -1:
		TransactionManager.Instance.EnsureInTransaction(doc)	
		sectionView = ViewSection.CreateDetail(doc, viewFamilyTypeId, boundingBox) # http://www.revitapidocs.com/2016/834e7154-b2f0-ffcd-b04a-9ad8cee321c8.htm
		TransactionManager.Instance.TransactionTaskDone()
		return sectionView


def exportViewImage(view, path, pixel_size):
	ieo = ImageExportOptions()
	ieo.ExportRange = ExportRange.SetOfViews
	ieo.SetViewsAndSheets([view.Id])
	ieo.ViewName = view.ViewName
	ieo.FilePath = path	
	ieo.HLRandWFViewsFileType = ImageFileType.PNG
	ieo.ShadowViewsFileType = ImageFileType.PNG
	#ieo.PixelSize = pixel_size
	doc.ExportImage(ieo)
	return ieo


def scopeBox2cropBox(scopeBox, viewFamilyTypeId, bbx):
	TransactionManager.Instance.EnsureInTransaction(doc)
	sectionView = ViewSection.CreateDetail(doc, viewFamilyTypeId, bbx) # http://www.revitapidocs.com/2016/834e7154-b2
	param = sectionView.get_Parameter(BuiltInParameter.VIEWER_VOLUME_OF_INTEREST_CROP)
	param.Set(scopeBox.Id)
	TransactionManager.Instance.TransactionTaskDone()
	return sectionView


filePath = IN[0]
voxel_size = IN[1]
scopeBox = UnwrapElement(IN[2])
doc = DocumentManager.Instance.CurrentDBDocument
try:
	pre_i = 0 # slow issue: delete the first picture
	pre_j = 0
	count = -1
	
	viewFamilyTypeId = get_ViewFamilyTypeId("Detail View")
	boundingBox = BoundingBoxXYZ() 
	sectionView = scopeBox2cropBox(scopeBox, viewFamilyTypeId, boundingBox)
	
	cropBox = sectionView.CropBox
	minPoint = cropBox.Min
	maxPoint = cropBox.Max
	bottom = minPoint.Z
	top = maxPoint.Z
	height = 0
	digit = len(str(int((top - bottom) / voxel_size))) 
	
	secionViews = []
	
	while height + bottom &lt; top:
		if count &gt; 50:
			break
	
		height += voxel_size # trigger 1st round
		bbx = BoundingBoxXYZ()
		bbx.Min = XYZ(minPoint.X, minPoint.Y, min(minPoint.Z + height, maxPoint.Z) + 200)
		bbx.Max = XYZ(maxPoint.X, maxPoint.Y, maxPoint.Z + 200)
		sectionView_t = create_view(doc, viewFamilyTypeId, bbx)
		secionViews.append(sectionView_t)
			
		#bbox = sectionView.CropBox # get view's cropbox coordinates
		#pixel_size = (bbox.Max.X - bbox.Min.X) * 12 * voxel_size
		
		pixel_size = 0.01 * 12 * voxel_size # trigger 2nd round
		imageName = filePath + str(count).rjust(digit)
		ieo = exportViewImage(sectionView_t, imageName, pixel_size)
			
		count += 1
		
	OUT = "succeed", sectionView, bottom, top, secionViews
except Exception as e:
	OUT =  e
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d5c1fe87-270a-4c1b-9e06-f0552677a491" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="757.089531535513" y="50.4515055008084" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;C:\Dynamo\ViewRange\\test_views\slice1&quot;;&#xA;1;&#xA;&quot;Scope Box 3&quot;;" ShouldFocus="false" />
    <DSRevitNodesUI.Categories guid="0ac7e01e-a7a9-4303-b005-774a067227d1" type="DSRevitNodesUI.Categories" nickname="Categories" x="417.981156190448" y="291.583260967862" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="387:VolumeOfInterest" />
    <DSRevitNodesUI.ElementsOfCategory guid="f85e13f9-fc10-4633-8c7b-0f97c096a2db" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="600.351952806209" y="299.706628066686" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6c1931d9-82ba-49b7-912e-87fa4efa5eac" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="1145.90383013797" y="341.559332245561" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="785b7cbd-f4c0-4d9e-9250-f83041b2048c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Name" x="707.341448788196" y="409.188110678003" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="45a4b0cd-8901-4ad0-84f9-12d576521c53" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="==" x="947.116208685036" y="405.089396833612" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="Operators" function="==@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="53050d86-dd90-4e92-ae3b-fc9983bd2c3e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Parameters" x="1533.71606054854" y="400.89902659984" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Parameters">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="9e2cc822-7ab5-48c6-90f6-a74c691943f4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1288.62209486098" y="228.29274681134" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="0" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="1" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5c1fe87-270a-4c1b-9e06-f0552677a491" start_index="2" end="45a4b0cd-8901-4ad0-84f9-12d576521c53" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ac7e01e-a7a9-4303-b005-774a067227d1" start_index="0" end="f85e13f9-fc10-4633-8c7b-0f97c096a2db" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f85e13f9-fc10-4633-8c7b-0f97c096a2db" start_index="0" end="6c1931d9-82ba-49b7-912e-87fa4efa5eac" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f85e13f9-fc10-4633-8c7b-0f97c096a2db" start_index="0" end="785b7cbd-f4c0-4d9e-9250-f83041b2048c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c1931d9-82ba-49b7-912e-87fa4efa5eac" start_index="0" end="53050d86-dd90-4e92-ae3b-fc9983bd2c3e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c1931d9-82ba-49b7-912e-87fa4efa5eac" start_index="0" end="9e2cc822-7ab5-48c6-90f6-a74c691943f4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="785b7cbd-f4c0-4d9e-9250-f83041b2048c" start_index="0" end="45a4b0cd-8901-4ad0-84f9-12d576521c53" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45a4b0cd-8901-4ad0-84f9-12d576521c53" start_index="0" end="6c1931d9-82ba-49b7-912e-87fa4efa5eac" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9e2cc822-7ab5-48c6-90f6-a74c691943f4" start_index="0" end="de398f19-9dda-4448-b260-d97475bc1588" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>